/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.GridBagConstraints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author intec
 */
public class CaptureDataDialogCustom extends javax.swing.JDialog {

    private GridBagConstraints textFieldConstraints;
    static List<JTextField> listOfTextFields = new ArrayList<>();

    public static List<JTextField> getListOfTextFields() {
        return listOfTextFields;
    }

    public static void setListOfTextFields(List<JTextField> listOfTextFields) {
        CaptureDataDialogCustom.listOfTextFields = listOfTextFields;
    }

    /**
     * Creates new form CaptureDataDialog
     *
     * @param parent
     * @param modal
     */
    public CaptureDataDialogCustom(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.listOfTextFields = listOfTextFields;
        textFieldConstraints = new GridBagConstraints();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        captureDataBagContainer = new javax.swing.JPanel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        captureDataBagContainer.setLayout(new java.awt.GridBagLayout());
        // Add labels and text fields
        for (int i = 0; i < listOfTextFields.size(); i++) {
            // Text field constraints
            textFieldConstraints.gridx = 0;
            textFieldConstraints.gridy = i;
            textFieldConstraints.gridwidth = 1;
            textFieldConstraints.gridheight = 1;
            captureDataBagContainer.add(listOfTextFields.get(i), textFieldConstraints);
        }
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(335, Short.MAX_VALUE)
                        .addComponent(captureDataBagContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(captureDataBagContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(261, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JPanel captureDataBagContainer;
    // End of variables declaration                   
}
