/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author intec
 */
public class CreateDataDialog extends javax.swing.JDialog {

    /**
     * Creates new form createDataDialog
     */
    public CreateDataDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creationDataPane = new javax.swing.JPanel();
        createDataTitleLabel = new javax.swing.JLabel();
        dataDocumentLabel = new javax.swing.JLabel();
        nameDataField = new javax.swing.JLabel();
        dataTypeLabel = new javax.swing.JLabel();
        cleanDataButton = new javax.swing.JButton();
        nameDataTxt = new javax.swing.JTextField();
        createDataButton = new javax.swing.JButton();
        selectedDocumentLabel = new javax.swing.JLabel();
        dataTypeSelector = new javax.swing.JComboBox();
        isRequiredDataLabel = new javax.swing.JLabel();
        isRequiredDataCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Nuevo Dato");
        setResizable(false);

        createDataTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createDataTitleLabel.setForeground(new java.awt.Color(153, 153, 153));
        createDataTitleLabel.setText("Agregar Nuevo Dato");
        createDataTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        createDataTitleLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        dataDocumentLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataDocumentLabel.setForeground(new java.awt.Color(153, 153, 153));
        dataDocumentLabel.setText("Documento:");

        nameDataField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameDataField.setForeground(new java.awt.Color(153, 153, 153));
        nameDataField.setText("Nombre:");

        dataTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataTypeLabel.setForeground(new java.awt.Color(153, 153, 153));
        dataTypeLabel.setText("Tipo de dato:");

        cleanDataButton.setText("Limpiar");
        cleanDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanDataButtonActionPerformed(evt);
            }
        });

        createDataButton.setText("Crear");
        createDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDataButtonActionPerformed(evt);
            }
        });

        dataTypeSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        isRequiredDataLabel.setText("Es requerido:");

        javax.swing.GroupLayout creationDataPaneLayout = new javax.swing.GroupLayout(creationDataPane);
        creationDataPane.setLayout(creationDataPaneLayout);
        creationDataPaneLayout.setHorizontalGroup(
            creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationDataPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cleanDataButton)
                .addGap(27, 27, 27)
                .addComponent(createDataButton))
            .addGroup(creationDataPaneLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(createDataTitleLabel)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(creationDataPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataDocumentLabel)
                    .addComponent(nameDataField)
                    .addComponent(dataTypeLabel)
                    .addComponent(isRequiredDataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isRequiredDataCheckBox)
                    .addGroup(creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameDataTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addComponent(selectedDocumentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataTypeSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        creationDataPaneLayout.setVerticalGroup(
            creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationDataPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(createDataTitleLabel)
                .addGap(45, 45, 45)
                .addGroup(creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDocumentLabel)
                    .addComponent(selectedDocumentLabel))
                .addGap(35, 35, 35)
                .addGroup(creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDataField))
                .addGap(31, 31, 31)
                .addGroup(creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataTypeLabel)
                    .addComponent(dataTypeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isRequiredDataLabel)
                    .addComponent(isRequiredDataCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(creationDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanDataButton)
                    .addComponent(createDataButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(creationDataPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creationDataPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDataButtonActionPerformed

    }//GEN-LAST:event_createDataButtonActionPerformed

    private void cleanDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanDataButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateDataDialog dialog = new CreateDataDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanDataButton;
    private javax.swing.JButton createDataButton;
    private javax.swing.JLabel createDataTitleLabel;
    private javax.swing.JPanel creationDataPane;
    private javax.swing.JLabel dataDocumentLabel;
    private javax.swing.JLabel dataTypeLabel;
    private javax.swing.JComboBox dataTypeSelector;
    private javax.swing.JCheckBox isRequiredDataCheckBox;
    private javax.swing.JLabel isRequiredDataLabel;
    private javax.swing.JLabel nameDataField;
    private javax.swing.JTextField nameDataTxt;
    private javax.swing.JLabel selectedDocumentLabel;
    // End of variables declaration//GEN-END:variables
}
