/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author intec
 */
public class CreateDocumentDialog extends javax.swing.JDialog {

    /**
     * Creates new form createDocumentDialog
     */
    public CreateDocumentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creationDocumentPane = new javax.swing.JPanel();
        createDocumentTitleLabel = new javax.swing.JLabel();
        nameDocumentLabel = new javax.swing.JLabel();
        descriptionNameLabel = new javax.swing.JLabel();
        expedientIncludeLabel = new javax.swing.JLabel();
        cleanDocumentButton = new javax.swing.JButton();
        nameDocumentTxt = new javax.swing.JTextField();
        descriptionDocumentTxt = new javax.swing.JTextField();
        creationDocumentScroll = new javax.swing.JScrollPane();
        ExpedientList = new javax.swing.JList();
        createDocumentButton = new javax.swing.JButton();
        maxImageSizeLabel = new javax.swing.JLabel();
        maxImageSizeTxt = new javax.swing.JTextField();
        documentRepeatLabel = new javax.swing.JLabel();
        documentRepeatCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        documentExpireCheckBox = new javax.swing.JCheckBox();
        documentRequeridedCheckBox = new javax.swing.JCheckBox();
        resolutionLabel = new javax.swing.JLabel();
        resolutionCheckBox = new javax.swing.JCheckBox();
        resolutionTextArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        createDocumentTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createDocumentTitleLabel.setForeground(new java.awt.Color(153, 153, 153));
        createDocumentTitleLabel.setText("Crear Nuevo Documento");
        createDocumentTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        createDocumentTitleLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        nameDocumentLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameDocumentLabel.setForeground(new java.awt.Color(153, 153, 153));
        nameDocumentLabel.setText("Nombre:");

        descriptionNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descriptionNameLabel.setForeground(new java.awt.Color(153, 153, 153));
        descriptionNameLabel.setText("Descripción:");

        expedientIncludeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expedientIncludeLabel.setForeground(new java.awt.Color(153, 153, 153));
        expedientIncludeLabel.setText("Incluir a Expediente:");

        cleanDocumentButton.setText("Limpiar");

        ExpedientList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        creationDocumentScroll.setViewportView(ExpedientList);

        createDocumentButton.setText("Crear");
        createDocumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDocumentButtonActionPerformed(evt);
            }
        });

        maxImageSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maxImageSizeLabel.setForeground(new java.awt.Color(153, 153, 153));
        maxImageSizeLabel.setText("Tamaño Máximo de Imágen:");

        documentRepeatLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        documentRepeatLabel.setForeground(new java.awt.Color(153, 153, 153));
        documentRepeatLabel.setText("Documento repetitivo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Documento Expira:");

        resolutionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resolutionLabel.setForeground(new java.awt.Color(153, 153, 153));
        resolutionLabel.setText("Resolución:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Documento Requerido:");

        javax.swing.GroupLayout creationDocumentPaneLayout = new javax.swing.GroupLayout(creationDocumentPane);
        creationDocumentPane.setLayout(creationDocumentPaneLayout);
        creationDocumentPaneLayout.setHorizontalGroup(
            creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(createDocumentTitleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creationDocumentPaneLayout.createSequentialGroup()
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addComponent(expedientIncludeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(creationDocumentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionNameLabel)
                            .addComponent(nameDocumentLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDocumentTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionDocumentTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cleanDocumentButton)
                        .addGap(30, 30, 30)
                        .addComponent(createDocumentButton))
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxImageSizeLabel)
                            .addComponent(documentRepeatLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1))
                            .addComponent(resolutionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resolutionCheckBox)
                            .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(documentRepeatCheckBox)
                                .addComponent(maxImageSizeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(documentExpireCheckBox)
                                .addComponent(documentRequeridedCheckBox)
                                .addComponent(resolutionTextArea)))))
                .addGap(60, 60, 60))
        );
        creationDocumentPaneLayout.setVerticalGroup(
            creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                .addComponent(createDocumentTitleLabel)
                .addGap(24, 24, 24)
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDocumentLabel)
                    .addComponent(nameDocumentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionNameLabel)
                    .addComponent(descriptionDocumentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expedientIncludeLabel)
                    .addComponent(creationDocumentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(maxImageSizeLabel))
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maxImageSizeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(documentRepeatLabel)
                    .addComponent(documentRepeatCheckBox))
                .addGap(18, 18, 18)
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(documentExpireCheckBox))
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(documentRequeridedCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addComponent(resolutionLabel)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(creationDocumentPaneLayout.createSequentialGroup()
                        .addComponent(resolutionCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resolutionTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(creationDocumentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanDocumentButton)
                    .addComponent(createDocumentButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(creationDocumentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creationDocumentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDocumentButtonActionPerformed

    }//GEN-LAST:event_createDocumentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDocumentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDocumentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDocumentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDocumentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateDocumentDialog dialog = new CreateDocumentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ExpedientList;
    private javax.swing.JButton cleanDocumentButton;
    private javax.swing.JButton createDocumentButton;
    private javax.swing.JLabel createDocumentTitleLabel;
    private javax.swing.JPanel creationDocumentPane;
    private javax.swing.JScrollPane creationDocumentScroll;
    private javax.swing.JTextField descriptionDocumentTxt;
    private javax.swing.JLabel descriptionNameLabel;
    private javax.swing.JCheckBox documentExpireCheckBox;
    private javax.swing.JCheckBox documentRepeatCheckBox;
    private javax.swing.JLabel documentRepeatLabel;
    private javax.swing.JCheckBox documentRequeridedCheckBox;
    private javax.swing.JLabel expedientIncludeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel maxImageSizeLabel;
    private javax.swing.JTextField maxImageSizeTxt;
    private javax.swing.JLabel nameDocumentLabel;
    private javax.swing.JTextField nameDocumentTxt;
    private javax.swing.JCheckBox resolutionCheckBox;
    private javax.swing.JLabel resolutionLabel;
    private javax.swing.JTextField resolutionTextArea;
    // End of variables declaration//GEN-END:variables
}
