/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author intec
 */
public class RegistPersonDialog extends javax.swing.JDialog {

    /**
     * Creates new form RegistPersonDialog
     */
    public RegistPersonDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idenTypeSelectorLabel = new javax.swing.JLabel();
        identificationNumberLabel = new javax.swing.JLabel();
        nameRegistPersonLabel = new javax.swing.JLabel();
        nationSelectorRegistPersonLabel = new javax.swing.JLabel();
        registPersonButton = new javax.swing.JButton();
        cleanRegistPersonButton = new javax.swing.JButton();
        identificacionNumberTxt = new javax.swing.JTextField();
        idenTypeSelector = new javax.swing.JComboBox();
        nameRegistPersonTxt = new javax.swing.JTextField();
        verifyDocumentButton = new javax.swing.JButton();
        nationalityTxt = new javax.swing.JComboBox();
        registPersonTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Persona");

        idenTypeSelectorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idenTypeSelectorLabel.setForeground(new java.awt.Color(153, 153, 153));
        idenTypeSelectorLabel.setText("Tipo Identificación:");

        identificationNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        identificationNumberLabel.setForeground(new java.awt.Color(153, 153, 153));
        identificationNumberLabel.setText("Número de Identificación:");

        nameRegistPersonLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameRegistPersonLabel.setForeground(new java.awt.Color(153, 153, 153));
        nameRegistPersonLabel.setText("Nombre:");

        nationSelectorRegistPersonLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nationSelectorRegistPersonLabel.setForeground(new java.awt.Color(153, 153, 153));
        nationSelectorRegistPersonLabel.setText("Nacionalidad:");

        registPersonButton.setText("Guardar");

        cleanRegistPersonButton.setText("Limpiar");

        idenTypeSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idenTypeSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idenTypeSelectorActionPerformed(evt);
            }
        });

        verifyDocumentButton.setText("Verificación de Documentos");

        nationalityTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        registPersonTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registPersonTitle.setForeground(new java.awt.Color(153, 153, 153));
        registPersonTitle.setText("Registro de Persona");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(verifyDocumentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(cleanRegistPersonButton)
                                .addGap(18, 18, 18)
                                .addComponent(registPersonButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idenTypeSelectorLabel)
                                    .addComponent(identificationNumberLabel)
                                    .addComponent(nameRegistPersonLabel)
                                    .addComponent(nationSelectorRegistPersonLabel))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(identificacionNumberTxt)
                                    .addComponent(idenTypeSelector, 0, 147, Short.MAX_VALUE)
                                    .addComponent(nameRegistPersonTxt)
                                    .addComponent(nationalityTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(registPersonTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registPersonTitle)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idenTypeSelectorLabel)
                    .addComponent(idenTypeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificationNumberLabel)
                    .addComponent(identificacionNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRegistPersonLabel)
                    .addComponent(nameRegistPersonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationSelectorRegistPersonLabel)
                    .addComponent(nationalityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registPersonButton)
                    .addComponent(cleanRegistPersonButton)
                    .addComponent(verifyDocumentButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idenTypeSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idenTypeSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idenTypeSelectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistPersonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistPersonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistPersonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistPersonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistPersonDialog dialog = new RegistPersonDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanRegistPersonButton;
    private javax.swing.JComboBox idenTypeSelector;
    private javax.swing.JLabel idenTypeSelectorLabel;
    private javax.swing.JTextField identificacionNumberTxt;
    private javax.swing.JLabel identificationNumberLabel;
    private javax.swing.JLabel nameRegistPersonLabel;
    private javax.swing.JTextField nameRegistPersonTxt;
    private javax.swing.JLabel nationSelectorRegistPersonLabel;
    private javax.swing.JComboBox nationalityTxt;
    private javax.swing.JButton registPersonButton;
    private javax.swing.JLabel registPersonTitle;
    private javax.swing.JButton verifyDocumentButton;
    // End of variables declaration//GEN-END:variables
}
